service: reference-data-service-uploaders

provider:
  name: aws
  runtime: python3.7
  region: eu-west-2
  stage: ${opt:stage, 'test'}
  timeout: 10
  memorySize: 256
  vpc:
    securityGroupIds:
      - sg-078e4664ee69d99e5
      # - Fn::ImportValue: "test:RefDataUploaderLambdaSG"
    subnetIds:
      - Fn::ImportValue: "test:PrivateSubnetA"
      - Fn::ImportValue: "test:PrivateSubnetB"
  environment:
    RDS_HOST: "test:RdsHostName"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:ListBucket"
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - fdbt-csv-reference-data-${self:provider.stage}
        - Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - fdbt-xml-reference-data-${self:provider.stage}

plugins:
  - serverless-python-requirements

functions:
  CsvUploader:
    handler: csv-uploader/handler
    events:
      - s3:
        bucket: fdbt-csv-reference-data-${self:provider.stage}
        event: s3:ObjectCreated:*

  XmlUploader:
    handler: xml-uploader/handler
    events:
      - s3:
        bucket: fdbt-xml-reference-data-${self:provider.stage}
        event: s3:ObjectCreated:*

package:
  exclude:
    - node_modules/**
  include:
    - ./csv-uploader/*
    - ./xml-uploader/*
